<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
	<link rel="icon" href="img/AgenciaArcSystem_logo.png" type="AgenciaArcSystem_logo.png" />
    <title>Agencia ArcSystem - Solidariedade! Faça sua Doação</title>
<!-- FONTE -->
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,700&display=swap" rel="stylesheet">
<!-- BOOTSTRAP -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="css/styles.css">

<!-- SCRIPTS -->
    <script
    src="https://code.jquery.com/jquery-3.5.1.min.js"
    integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0="
    crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

<!-- FONT AWESOME -->
    <script src="https://kit.fontawesome.com/d918be3c7c.js" crossorigin="anonymous"></script>

<!-- PROGRESS BAR -->
    <Script src="js/progressbar.min.js"></Script>

<!-- PARALLAX -->
    <script src="https://cdn.jsdelivr.net/parallax.js/1.4.2/parallax.min.js"></script>

</head>
<body>

<!--TOP MENU -->
    <header>
        <div class="container" id="nav-container">
            <nav class=" navbar navbar-expand-lg fixed-top navbar-dark">
                <a href="#" class="navbar-brand">
                    <img id="logo" src="img/AgenciaArcSystem_logo.png" alt="Agencia ArcSystem"> Agencia ArcSystem
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-links" 
                    aria-controls="navbar-links" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse justify-content-end" id="navbar-links">
                    <div class="navbar-nav">
                        <a class="nav-item nav-link" id="home-menu" href="index.php">Home</a>
						<a class="nav-item nav-link" id="home-menu" href="form_doar.php">DOAR</a>
						<a class="nav-item nav-link" id="home-menu" href="lista_doadores.php">Lista de Doadores</a>
                        <a class="nav-item nav-link" id="about-menu" href="#">Sobre Nós</a>						
                        <a class="nav-item nav-link" id="services-menu" href="#">Serviços</a>
                        <a class="nav-item nav-link" id="team-menu" href="#">Time/Equipes</a>
                        <a class="nav-item nav-link" id="portfolio-menu" href="#">Projetos</a>
                        <a class="nav-item nav-link" id="contact-menu" href="#">Contatos</a>
                    </div>
                </div>
            </nav>
        </div>
    </header>