<footer>
	| <a href="form_doar.php">DOAR</a> |
	| <a href="lista_doadores.php">Lista de Doadores</a> |
	| <a href="form_associar.php">Associar-se</a> |
	| <a href="lista_associados.php">Lista de Associados</a> |
    | <a href="encerrar_sessao.php">Limpar Sessão</a> |
<hr><hr>
	 <div id="copy-area">
		<div class="container">
			<div class="row">
				<div class="col-md-12">
					<p>Desenvolvido e Criado por <a href="https://github.com/NickWelber/Exercicios" target="_blank">Agencia ArcSystem</a> &copy; 2020</p>
				</div>
			</div>
		</div>
	</div>
</footer>

<!-- JAVASCRIPTS DO PROJETO -->
    <script src="js/scripts.js"></script>
</body>
</html>